### ISSUE TITLE
It would be better to manage the dependencies using gradle?

### ISSUE THREAD

**Issue by cs-jlopezr** [xcsp3team/ace#2]
Junit, Hamcrest, Json and XCSP3 libraries are used as jars in the project it would be better to delete the lib folder and add the corresponding dependencies in the build.gradle file.

testImplementation group: 'org.hamcrest', name: 'hamcrest-all', version: '1.3'
testImplementation group: 'junit', name: 'junit', version: '4.13.1'
implementation group: 'org.glassfish', name: 'javax.json', version: '1.0.4'
implementation 'org.xcsp:xcsp3-tools:2.0.1' (2.0.2 version still not available)

**Comment by xcsp3team** [comment]
Dear Jheisson,

  I will consider your issue in June (notably, I have to fix the problem with the 2.0.2 version).

 Thanks for your interest.
